### ISSUE TITLE
API key will be deprecated

### ISSUE THREAD

**Issue by kszymukowicz** [TYPO3GmbH/ext-hubspot#8]
hi
there is announcement of Hubspot that API key will be deprecated on 30 Nov 2022. https://developers.hubspot.com/changelog/upcoming-api-key-sunset

will that influence this extension?

**Comment by mabolek** [comment]
Hi @kszymukowicz!

Yes, it will influence this extension. Although it will be a breaking change, it looks like it will only require a change in a single line of code and one configuration property.

I'm working on implementing this.

**Comment by kszymukowicz** [comment]
Tnx!
